sudo: required
services:
  - docker

before_install:
  docker build -t msintaha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true msintaha/react-test npm test -- --coverage

after_success:
  - docker build -t msintaha/multi-client ./client
  - docker build -t msintaha/multi-server ./server
  - docker build -t msintaha/multi-worker ./worker
  - docker build -t msintaha/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push msintaha/multi-client
  - docker push msintaha/multi-server
  - docker push msintaha/multi-worker
  - docker push msintaha/multi-nginx

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucker_name: <bucket_name>
#   bucket_path: docker-multi
#   on:
#     branch: master
# access_key_id: $AWS_ACCESS_KEY # Stored in your travis-ci env variables
# secret_access_key: $AWS_SECRET_KEY # Stored in your travis-ci env variables