sudo: required
services:
  - docker

before_install:
  docker build -t msintaha/react-test ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true msintaha/react-test npm test -- --coverage

after_success:
  - docker build -t msintaha/multi-client ./client
  - docker build -t msintaha/multi-server ./server
  - docker build -t msintaha/multi-worker ./worker
  - docker build -t msintaha/multi-nginx ./nginx
